const events = [
    {
        "id" : 1, 
        "name": "Lazer Maze",
        "desc": "Maze created using lazers.",
        "isTeam": 1,
        "faculty_coordinator": "Dr. Amit Mondal",
        "student_coordinators": "Bilal | Joravar",
        "room": "B301",
        "day1": "16th : 11:00 am - 3:00 pm & 6:30 pm - 8:30 pm",
        "day2": "17th : 10:00 am - 1:00 pm",
        "judging_criteria": "Time",
        "src" : "/css/posters/Lazer_maze.gif"
    },
    {
        "id" : 2, 
        "name": "Electrothon",
        "desc": "Three mini games - buzzwire, japanese electronic game and carnival shooting game. Arduino circuit building.",
        "isTeam": 1,
        "faculty_coordinator": "Dr. Ravishankar Dudhe",
        "student_coordinators": "Silah | Rayyan",
        "room": "B309",
        "day1": "16th : 2:30 pm - 5:00 pm ",
        "day2": "17th : 10:00 am - 3:00 pm",
        "judging_criteria": "Time",
        "src" : "/css/posters/Electrothon.gif"
    },
    {
        "id" : 3, 
        "name": "Neon TechnoFun",
        "desc": "A Soccer game with RC cars.",
        "isTeam": 4,
        "faculty_coordinator": "Dr. Ravishankar Dudhe",
        "student_coordinators": "Noel | Karan",
        "room": "B311",
        "day1": "16th : 3:00 pm - 6:00 pm",
        "day2": "17th : 10:00 am - 3:00 pm",
        "judging_criteria": "Goals",
        "src" : "/css/posters/Neon_Rocket.png"
    },
    {
        "id" : 4, 
        "name": "Hydrojet",
        "desc": "Make a launch platform and launch a rocket using water bottles, propelled by pressurised water.",
        "isTeam": 1,
        "faculty_coordinator": "Sampath Suranjan",
        "student_coordinators": "Ahmed Fazal | Raj P",
        "room": "Hostel court",
        "day1": "17th : 10:30 am - 1:30 pm",
        "day2": "",
        "judging_criteria": "Flight Time and Distance",
        "src" : "/css/posters/HYDROJET.jpeg"
    },
    {
        "id" : 5, 
        "name": "Homeprotek",
        "desc": "Build a cardboard house with ventilation.",
        "isTeam": 4,
        "faculty_coordinator": "Sampath Suranjan",
        "student_coordinators": "Krishna Prasad | Pratyush",
        "room": "B411, B405",
        "day1": "16th : 10:30 am - 1:00 pm",
        "day2": "",
        "judging_criteria": "Temperature, Asthetics, Rigidity, Materials used",
        "src" : "/css/posters/HOMEPROTEK.jpeg"
    },
    {
        "id" : 6, 
        "name": "SniffLicious",
        "desc": "Make a perfume on the spot.",
        "isTeam": 1,
        "faculty_coordinator": "Vandana S",
        "student_coordinators": "Wendell Paul | Reihan Mujeeb",
        "room": "B302",
        "day1": "16th : 9:00 am - 2:00 pm",
        "day2": "17th : 9:00 am - 2:00 pm",
        "judging_criteria": "N/A",
        "src" : "/css/posters/Snifflicious.jpeg"
    },
    {
        "id" : 7, 
        "name": "Escape Room",
        "desc": "An elaborate puzzle for the quick- witted.",
        "isTeam": 2,
        "faculty_coordinator": "Surumi R",
        "student_coordinators": "Sara Biji | Huda",
        "room": "B105",
        "day1": "16th : 9:00 am - 5:00 pm",
        "day2": "17th : 9:00 am - 5:00 pm",
        "judging_criteria": "Time",
        "src" : "/css/posters/Escape_Room.png"
    },
    {
        "id" : 8, 
        "name": "Lost Treasure",
        "desc": "Clues to find a hidden item.",
        "isTeam": 4,
        "faculty_coordinator": "Deepa Varghese",
        "student_coordinators": "Basit | Aejaz",
        "room": "B103",
        "day1": "16th : 9:00 am - 5:00 pm",
        "day2": "17th : 9:00 am - 5:00 pm",
        "judging_criteria": "Time",
        "src" : "/css/posters/Lost_Treasure.png"
    },
    {
        "id" : 9, 
        "name": "Skedaddle Through Time",
        "desc": "A game with 3 stages - Cipher Game (beginning the storyline), Combat Game (with VR headsets and controllers) and Among Us (find the impostor).",
        "isTeam": 5,
        "faculty_coordinator": "Shoba Francis",
        "student_coordinators": "Sanchita | Astha | Hashim | Dhruv",
        "room": "AutoCAD Lab",
        "day1": "16th : 10:00 am - 3:30 pm",
        "day2": "",
        "judging_criteria": "Finding the Imposter",
        "src" : "/css/posters/Skedaddle_through_time_2.jpg"
        
    }
    
];